spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=GMT
    username: root
    password: sangxin59
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

#manager是所有actuator的配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有的监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有监控端点

  #endpoint.xxx 表示配置某个具体的监控端点
  endpoint:
    health:
      show-details: always #显示health监控端点的详细信息
